language: cpp
os: osx
osx_image: xcode10.2
git:
  depth: 3
env:
  matrix:
    - PACKAGE='CHECK'
    - PACKAGE='AABB_tree Advancing_front_surface_reconstruction Algebraic_foundations '
    - PACKAGE='Algebraic_kernel_d Algebraic_kernel_for_circles Algebraic_kernel_for_spheres '
    - PACKAGE='Alpha_shapes_2 Alpha_shapes_3 Apollonius_graph_2 '
    - PACKAGE='Arithmetic_kernel Arrangement_on_surface_2 Barycentric_coordinates_2 '
    - PACKAGE='BGL Boolean_set_operations_2 Bounding_volumes '
    - PACKAGE='Box_intersection_d Cartesian_kernel CGAL_Core '
    - PACKAGE='CGAL_ImageIO CGAL_ipelets Circular_kernel_2 '
    - PACKAGE='Circular_kernel_3 Circulator Classification '
    - PACKAGE='Combinatorial_map Cone_spanners_2 Convex_decomposition_3 '
    - PACKAGE='Convex_hull_2 Convex_hull_3 Convex_hull_d '
    - PACKAGE='Distance_2 Distance_3 Envelope_2 '
    - PACKAGE='Envelope_3 Filtered_kernel Generalized_map '
    - PACKAGE='Generator Geomview GraphicsView '
    - PACKAGE='HalfedgeDS Hash_map Heat_method_3 '
    - PACKAGE='Homogeneous_kernel Hyperbolic_triangulation_2 Inscribed_areas '
    - PACKAGE='Installation Interpolation Intersections_2 '
    - PACKAGE='Intersections_3 Interval_skip_list Interval_support '
    - PACKAGE='Inventor Jet_fitting_3 Kernel_23 '
    - PACKAGE='Kernel_d LEDA Linear_cell_complex '
    - PACKAGE='MacOSX Maintenance Matrix_search '
    - PACKAGE='Mesh_2 Mesh_3 Mesher_level '
    - PACKAGE='Minkowski_sum_2 Minkowski_sum_3 Modifier '
    - PACKAGE='Modular_arithmetic Nef_2 Nef_3 '
    - PACKAGE='Nef_S2 NewKernel_d Number_types '
    - PACKAGE='OpenNL Optimal_transportation_reconstruction_2 Optimisation_basic '
    - PACKAGE='Partition_2 Periodic_2_triangulation_2 Periodic_3_mesh_3 '
    - PACKAGE='Periodic_3_triangulation_3 Periodic_4_hyperbolic_triangulation_2 Point_set_2 '
    - PACKAGE='Point_set_3 Point_set_processing_3 Point_set_shape_detection_3 '
    - PACKAGE='Poisson_surface_reconstruction_3 Polygon Polygon_mesh_processing '
    - PACKAGE='Polyhedron Polyhedron_IO Polyline_simplification_2 '
    - PACKAGE='Polynomial Polytope_distance_d Principal_component_analysis '
    - PACKAGE='Principal_component_analysis_LGPL Profiling_tools Property_map '
    - PACKAGE='QP_solver Random_numbers Ridges_3 '
    - PACKAGE='Scale_space_reconstruction_3 Scripts SearchStructures '
    - PACKAGE='Segment_Delaunay_graph_2 Segment_Delaunay_graph_Linf_2 Set_movable_separability_2 '
    - PACKAGE='Skin_surface_3 Snap_rounding_2 Solver_interface '
    - PACKAGE='Spatial_searching Spatial_sorting STL_Extension '
    - PACKAGE='Straight_skeleton_2 Stream_lines_2 Stream_support '
    - PACKAGE='Subdivision_method_3 Surface_mesh Surface_mesh_approximation '
    - PACKAGE='Surface_mesh_deformation Surface_mesher Surface_mesh_parameterization '
    - PACKAGE='Surface_mesh_segmentation Surface_mesh_shortest_path Surface_mesh_simplification '
    - PACKAGE='Surface_mesh_skeletonization Surface_sweep_2 TDS_2 '
    - PACKAGE='TDS_3 Testsuite Three '
    - PACKAGE='Triangulation Triangulation_2 Triangulation_3 '
    - PACKAGE='Union_find Visibility_2 Voronoi_diagram_2 '
    - PACKAGE='wininst '
compiler: clang
install:
  - echo "$PWD"
  - if [ -n "$TRAVIS_PULL_REQUEST" ] && [ "$PACKAGE" != CHECK ]; then  DO_IGNORE=FALSE;  for ARG in $(echo "$PACKAGE");do if [ "$ARG" = "Maintenance" ]; then continue; fi; . $PWD/.travis/test_package.sh "$PWD" "$ARG";  echo "DO_IGNORE is $DO_IGNORE";  if [ "$DO_IGNORE" = "FALSE" ]; then  break; fi; done; if [ "$DO_IGNORE" = "TRUE" ]; then travis_terminate 0; fi;fi
  - /usr/bin/time  bash .travis/install.sh
  - export CXX=clang++ CC=clang;
before_script:
  - mkdir -p build
  - cd build
  - /usr/bin/time  cmake -DCMAKE_CXX_FLAGS="-std=c++11" -DCGAL_HEADER_ONLY=ON -DCMAKE_CXX_FLAGS_RELEASE=-DCGAL_NDEBUG -DWITH_examples=ON -DWITH_demos=ON -DWITH_tests=ON ..
  - /usr/bin/time  make
  - /usr/bin/time  sudo make install &>/dev/null
  - cd ..
script:
  - cd ./.travis
  - /usr/bin/time  bash ./build_package.sh $PACKAGE
notifications:
  email:
    on_success: change
    # default: always
    on_failure: always
    # default: always
